export const  ActionTypes = {
  SET_COALITIONS_NUMBER_OF_PLAYERS: 'SET_COALITIONS_NUMBER_OF_PLAYERS',
  SET_COALITIONS_GAME_DEFINITION: 'SET_COALITIONS_GAME_DEFINITION',
  SET_COALITIONS_SHAPLEY_VALUES: 'SET_COALITIONS_SHAPLEY_VALUES',
  SET_MCNETS_NUMBER_OF_PLAYERS: 'SET_MCNETS_NUMBER_OF_PLAYERS',
  SET_GRAPH_GAME_DEFINITION: 'SET_GRAPH_GAME_DEFINITION',
}

export default ActionTypes